# Generated by Django 3.1.7 on 2021-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='receiver_msg_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
