# Generated by Django 3.1.7 on 2021-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_receiver_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'отправлено юристу'), ('IN_PROCESS', 'на рассмотрении'), ('SUCCESS', 'согласованно')], default='CREATED', max_length=50),
        ),
    ]
