# Generated by Django 3.1.7 on 2021-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_consultation_tg_last_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
