# Generated by Django 3.1.7 on 2021-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultation_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'отправлено юристу'), ('IN_PROCESS', 'на рассмотрении'), ('SUCCESS', 'ответил')], default='CREATED', max_length=50),
        ),
    ]
