# Generated by Django 3.1.7 on 2021-04-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210406_1928'),
        ('territory', '0002_auto_20210406_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='territory',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.botuser'),
        ),
    ]
