# Generated by Django 3.1.7 on 2021-04-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_botuser_language'),
        ('territory', '0003_auto_20210406_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='account.botuser'),
        ),
    ]
