# Generated by Django 3.1.7 on 2021-04-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0004_auto_20210413_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='territory',
            name='name_uz',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
