apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-template
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-image
          image: {{.Values.image}}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: {{ .Release.Name }}-secrets
          ports:
            - containerPort: 8000
          lifecycle:
            postStart:
              exec:
                command: ["gunicorn", "--bind", "0.0.0.0:8000", "--max-requests", "50", "app.wsgi"]
