apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Release.Name }}-ingress-route
spec:
  virtualhost:
    fqdn: {{ .Values.ingress.host }}
  routes:
    - conditions:
        - prefix: /
      permitInsecure: true
      services:
        - name: {{ .Release.Name }}-service
          port: 80
