apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  database_url: {{.Values.database_url | b64enc}}
  bot_token: {{ .Values.bot_token | b64enc }}
  aws_access_key_id: {{ .Values.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key | b64enc }}
  aws_storage_bucket_name: {{ .Values.aws_storage_bucket_name | b64enc }}
  aws_media_bucket_name: {{ .Values.aws_media_bucket_name | b64enc }}
  aws_s3_region_name: {{ .Values.aws_s3_region_name | b64enc }}
