apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: 80
      protocol: TCP
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bot-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    project: {{ .Release.Name }}-bot
  ports:
    - name: {{ .Release.Name }}-bot-listener
      port: 80
      protocol: TCP
      targetPort: 8888
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    pod: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379