apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: 443
      protocol: TCP
      targetPort: 8000
  type: ClusterIP