# Generated by Django 3.1.7 on 2021-03-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
        ('account', '0002_auto_20210325_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='territory.territory'),
        ),
    ]
