# Generated by Django 3.1.7 on 2021-04-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210326_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
