# Generated by Django 3.1.7 on 2021-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210406_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
