# Generated by Django 3.1.7 on 2021-03-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territory', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_description', models.CharField(blank=True, max_length=128, null=True)),
                ('owner_file', models.FileField(upload_to='')),
                ('receiver_description', models.CharField(blank=True, max_length=128, null=True)),
                ('receiver_file', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_applications', to='account.botuser')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='account.botuser')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='territory.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
