# Generated by Django 3.1.7 on 2021-04-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210406_1928'),
        ('application', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner_file',
            field=models.FileField(upload_to='owner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='account.botuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='receiver_file',
            field=models.FileField(upload_to='receiver'),
        ),
    ]
