# Generated by Django 3.1.7 on 2021-04-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0003_auto_20210406_2152'),
        ('account', '0004_auto_20210406_1928'),
        ('application', '0003_auto_20210406_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_applications', to='account.botuser'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner_file',
            field=models.FileField(blank=True, null=True, upload_to='owner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='account.botuser'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receiver_file',
            field=models.FileField(blank=True, null=True, upload_to='receiver'),
        ),
        migrations.AlterField(
            model_name='application',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='territory.territory'),
        ),
    ]
