# Generated by Django 3.1.7 on 2021-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210406_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='receiver_msg_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
