# Generated by Django 3.1.7 on 2021-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_receiver_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tg_owner_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tg_receiver_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
