# Generated by Django 3.1.7 on 2021-04-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210407_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='transfer_risk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
