# Generated by Django 3.1.7 on 2021-04-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210407_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tg_last_kb',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
