# Generated by Django 3.1.7 on 2021-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_tg_last_kb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receiver_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/receiver'),
        ),
    ]
